// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/storage.proto

package storagepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReadStorageObjectsRequest struct {
	state         protoimpl.MessageState              `protogen:"open.v1"`
	ObjectIds     []*ReadStorageObjectsRequest_ReadOp `protobuf:"bytes,1,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStorageObjectsRequest) Reset() {
	*x = ReadStorageObjectsRequest{}
	mi := &file_api_storage_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStorageObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStorageObjectsRequest) ProtoMessage() {}

func (x *ReadStorageObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStorageObjectsRequest.ProtoReflect.Descriptor instead.
func (*ReadStorageObjectsRequest) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{0}
}

func (x *ReadStorageObjectsRequest) GetObjectIds() []*ReadStorageObjectsRequest_ReadOp {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

type StorageObject struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Collection      string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UserId          string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Value           string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"` // JSON string format
	Version         string                 `protobuf:"bytes,5,opt,name=version,proto3" json:"version,omitempty"`
	PermissionRead  int32                  `protobuf:"varint,6,opt,name=permission_read,json=permissionRead,proto3" json:"permission_read,omitempty"`
	PermissionWrite int32                  `protobuf:"varint,7,opt,name=permission_write,json=permissionWrite,proto3" json:"permission_write,omitempty"`
	CreateTime      *timestamppb.Timestamp `protobuf:"bytes,8,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime      *timestamppb.Timestamp `protobuf:"bytes,9,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *StorageObject) Reset() {
	*x = StorageObject{}
	mi := &file_api_storage_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageObject) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageObject) ProtoMessage() {}

func (x *StorageObject) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageObject.ProtoReflect.Descriptor instead.
func (*StorageObject) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{1}
}

func (x *StorageObject) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *StorageObject) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StorageObject) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StorageObject) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StorageObject) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StorageObject) GetPermissionRead() int32 {
	if x != nil {
		return x.PermissionRead
	}
	return 0
}

func (x *StorageObject) GetPermissionWrite() int32 {
	if x != nil {
		return x.PermissionWrite
	}
	return 0
}

func (x *StorageObject) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *StorageObject) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type StorageObjects struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*StorageObject       `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageObjects) Reset() {
	*x = StorageObjects{}
	mi := &file_api_storage_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageObjects) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageObjects) ProtoMessage() {}

func (x *StorageObjects) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageObjects.ProtoReflect.Descriptor instead.
func (*StorageObjects) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{2}
}

func (x *StorageObjects) GetObjects() []*StorageObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

type WriteStorageObjectsRequest struct {
	state         protoimpl.MessageState                `protogen:"open.v1"`
	Objects       []*WriteStorageObjectsRequest_WriteOp `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStorageObjectsRequest) Reset() {
	*x = WriteStorageObjectsRequest{}
	mi := &file_api_storage_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStorageObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStorageObjectsRequest) ProtoMessage() {}

func (x *WriteStorageObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStorageObjectsRequest.ProtoReflect.Descriptor instead.
func (*WriteStorageObjectsRequest) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{3}
}

func (x *WriteStorageObjectsRequest) GetObjects() []*WriteStorageObjectsRequest_WriteOp {
	if x != nil {
		return x.Objects
	}
	return nil
}

type StorageObjectAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Version       string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	CreateTime    *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	UpdateTime    *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=update_time,json=updateTime,proto3" json:"update_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageObjectAck) Reset() {
	*x = StorageObjectAck{}
	mi := &file_api_storage_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageObjectAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageObjectAck) ProtoMessage() {}

func (x *StorageObjectAck) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageObjectAck.ProtoReflect.Descriptor instead.
func (*StorageObjectAck) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{4}
}

func (x *StorageObjectAck) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *StorageObjectAck) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StorageObjectAck) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *StorageObjectAck) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *StorageObjectAck) GetCreateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CreateTime
	}
	return nil
}

func (x *StorageObjectAck) GetUpdateTime() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdateTime
	}
	return nil
}

type StorageObjectAcks struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Acks          []*StorageObjectAck    `protobuf:"bytes,1,rep,name=acks,proto3" json:"acks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageObjectAcks) Reset() {
	*x = StorageObjectAcks{}
	mi := &file_api_storage_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageObjectAcks) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageObjectAcks) ProtoMessage() {}

func (x *StorageObjectAcks) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageObjectAcks.ProtoReflect.Descriptor instead.
func (*StorageObjectAcks) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{5}
}

func (x *StorageObjectAcks) GetAcks() []*StorageObjectAck {
	if x != nil {
		return x.Acks
	}
	return nil
}

type DeleteStorageObjectsRequest struct {
	state         protoimpl.MessageState                  `protogen:"open.v1"`
	ObjectIds     []*DeleteStorageObjectsRequest_DeleteOp `protobuf:"bytes,1,rep,name=object_ids,json=objectIds,proto3" json:"object_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStorageObjectsRequest) Reset() {
	*x = DeleteStorageObjectsRequest{}
	mi := &file_api_storage_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStorageObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStorageObjectsRequest) ProtoMessage() {}

func (x *DeleteStorageObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStorageObjectsRequest.ProtoReflect.Descriptor instead.
func (*DeleteStorageObjectsRequest) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{6}
}

func (x *DeleteStorageObjectsRequest) GetObjectIds() []*DeleteStorageObjectsRequest_DeleteOp {
	if x != nil {
		return x.ObjectIds
	}
	return nil
}

type ListStorageObjectsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,3,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,4,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListStorageObjectsRequest) Reset() {
	*x = ListStorageObjectsRequest{}
	mi := &file_api_storage_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListStorageObjectsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListStorageObjectsRequest) ProtoMessage() {}

func (x *ListStorageObjectsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListStorageObjectsRequest.ProtoReflect.Descriptor instead.
func (*ListStorageObjectsRequest) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{7}
}

func (x *ListStorageObjectsRequest) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ListStorageObjectsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListStorageObjectsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListStorageObjectsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type StorageObjectList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Objects       []*StorageObject       `protobuf:"bytes,1,rep,name=objects,proto3" json:"objects,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StorageObjectList) Reset() {
	*x = StorageObjectList{}
	mi := &file_api_storage_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StorageObjectList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StorageObjectList) ProtoMessage() {}

func (x *StorageObjectList) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StorageObjectList.ProtoReflect.Descriptor instead.
func (*StorageObjectList) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{8}
}

func (x *StorageObjectList) GetObjects() []*StorageObject {
	if x != nil {
		return x.Objects
	}
	return nil
}

func (x *StorageObjectList) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type ReadStorageObjectsRequest_ReadOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStorageObjectsRequest_ReadOp) Reset() {
	*x = ReadStorageObjectsRequest_ReadOp{}
	mi := &file_api_storage_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStorageObjectsRequest_ReadOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStorageObjectsRequest_ReadOp) ProtoMessage() {}

func (x *ReadStorageObjectsRequest_ReadOp) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStorageObjectsRequest_ReadOp.ProtoReflect.Descriptor instead.
func (*ReadStorageObjectsRequest_ReadOp) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ReadStorageObjectsRequest_ReadOp) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *ReadStorageObjectsRequest_ReadOp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *ReadStorageObjectsRequest_ReadOp) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type WriteStorageObjectsRequest_WriteOp struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Collection      string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key             string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Value           string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"` // JSON string format
	Version         string                 `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
	PermissionRead  int32                  `protobuf:"varint,5,opt,name=permission_read,json=permissionRead,proto3" json:"permission_read,omitempty"`
	PermissionWrite int32                  `protobuf:"varint,6,opt,name=permission_write,json=permissionWrite,proto3" json:"permission_write,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WriteStorageObjectsRequest_WriteOp) Reset() {
	*x = WriteStorageObjectsRequest_WriteOp{}
	mi := &file_api_storage_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStorageObjectsRequest_WriteOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStorageObjectsRequest_WriteOp) ProtoMessage() {}

func (x *WriteStorageObjectsRequest_WriteOp) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStorageObjectsRequest_WriteOp.ProtoReflect.Descriptor instead.
func (*WriteStorageObjectsRequest_WriteOp) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{3, 0}
}

func (x *WriteStorageObjectsRequest_WriteOp) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *WriteStorageObjectsRequest_WriteOp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *WriteStorageObjectsRequest_WriteOp) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *WriteStorageObjectsRequest_WriteOp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *WriteStorageObjectsRequest_WriteOp) GetPermissionRead() int32 {
	if x != nil {
		return x.PermissionRead
	}
	return 0
}

func (x *WriteStorageObjectsRequest_WriteOp) GetPermissionWrite() int32 {
	if x != nil {
		return x.PermissionWrite
	}
	return 0
}

type DeleteStorageObjectsRequest_DeleteOp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Collection    string                 `protobuf:"bytes,1,opt,name=collection,proto3" json:"collection,omitempty"`
	Key           string                 `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	Version       string                 `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteStorageObjectsRequest_DeleteOp) Reset() {
	*x = DeleteStorageObjectsRequest_DeleteOp{}
	mi := &file_api_storage_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteStorageObjectsRequest_DeleteOp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteStorageObjectsRequest_DeleteOp) ProtoMessage() {}

func (x *DeleteStorageObjectsRequest_DeleteOp) ProtoReflect() protoreflect.Message {
	mi := &file_api_storage_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteStorageObjectsRequest_DeleteOp.ProtoReflect.Descriptor instead.
func (*DeleteStorageObjectsRequest_DeleteOp) Descriptor() ([]byte, []int) {
	return file_api_storage_proto_rawDescGZIP(), []int{6, 0}
}

func (x *DeleteStorageObjectsRequest_DeleteOp) GetCollection() string {
	if x != nil {
		return x.Collection
	}
	return ""
}

func (x *DeleteStorageObjectsRequest_DeleteOp) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteStorageObjectsRequest_DeleteOp) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

var File_api_storage_proto protoreflect.FileDescriptor

const file_api_storage_proto_rawDesc = "" +
	"\n" +
	"\x11api/storage.proto\x12\x13ultimate.server.api\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc6\x01\n" +
	"\x19ReadStorageObjectsRequest\x12T\n" +
	"\n" +
	"object_ids\x18\x01 \x03(\v25.ultimate.server.api.ReadStorageObjectsRequest.ReadOpR\tobjectIds\x1aS\n" +
	"\x06ReadOp\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\"\xd8\x02\n" +
	"\rStorageObject\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x05 \x01(\tR\aversion\x12'\n" +
	"\x0fpermission_read\x18\x06 \x01(\x05R\x0epermissionRead\x12)\n" +
	"\x10permission_write\x18\a \x01(\x05R\x0fpermissionWrite\x12;\n" +
	"\vcreate_time\x18\b \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\t \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"N\n" +
	"\x0eStorageObjects\x12<\n" +
	"\aobjects\x18\x01 \x03(\v2\".ultimate.server.api.StorageObjectR\aobjects\"\xb1\x02\n" +
	"\x1aWriteStorageObjectsRequest\x12Q\n" +
	"\aobjects\x18\x01 \x03(\v27.ultimate.server.api.WriteStorageObjectsRequest.WriteOpR\aobjects\x1a\xbf\x01\n" +
	"\aWriteOp\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12'\n" +
	"\x0fpermission_read\x18\x05 \x01(\x05R\x0epermissionRead\x12)\n" +
	"\x10permission_write\x18\x06 \x01(\x05R\x0fpermissionWrite\"\xf1\x01\n" +
	"\x10StorageObjectAck\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x18\n" +
	"\aversion\x18\x04 \x01(\tR\aversion\x12;\n" +
	"\vcreate_time\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"createTime\x12;\n" +
	"\vupdate_time\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\n" +
	"updateTime\"N\n" +
	"\x11StorageObjectAcks\x129\n" +
	"\x04acks\x18\x01 \x03(\v2%.ultimate.server.api.StorageObjectAckR\x04acks\"\xcf\x01\n" +
	"\x1bDeleteStorageObjectsRequest\x12X\n" +
	"\n" +
	"object_ids\x18\x01 \x03(\v29.ultimate.server.api.DeleteStorageObjectsRequest.DeleteOpR\tobjectIds\x1aV\n" +
	"\bDeleteOp\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x10\n" +
	"\x03key\x18\x02 \x01(\tR\x03key\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\"\x82\x01\n" +
	"\x19ListStorageObjectsRequest\x12\x1e\n" +
	"\n" +
	"collection\x18\x01 \x01(\tR\n" +
	"collection\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x03 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x04 \x01(\tR\x06cursor\"r\n" +
	"\x11StorageObjectList\x12<\n" +
	"\aobjects\x18\x01 \x03(\v2\".ultimate.server.api.StorageObjectR\aobjects\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor2\xbb\x03\n" +
	"\x0eStorageService\x12i\n" +
	"\x12ReadStorageObjects\x12..ultimate.server.api.ReadStorageObjectsRequest\x1a#.ultimate.server.api.StorageObjects\x12n\n" +
	"\x13WriteStorageObjects\x12/.ultimate.server.api.WriteStorageObjectsRequest\x1a&.ultimate.server.api.StorageObjectAcks\x12`\n" +
	"\x14DeleteStorageObjects\x120.ultimate.server.api.DeleteStorageObjectsRequest\x1a\x16.google.protobuf.Empty\x12l\n" +
	"\x12ListStorageObjects\x12..ultimate.server.api.ListStorageObjectsRequest\x1a&.ultimate.server.api.StorageObjectListB-Z+ultimate-game-server/internal/api/storagepbb\x06proto3"

var (
	file_api_storage_proto_rawDescOnce sync.Once
	file_api_storage_proto_rawDescData []byte
)

func file_api_storage_proto_rawDescGZIP() []byte {
	file_api_storage_proto_rawDescOnce.Do(func() {
		file_api_storage_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_storage_proto_rawDesc), len(file_api_storage_proto_rawDesc)))
	})
	return file_api_storage_proto_rawDescData
}

var file_api_storage_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_storage_proto_goTypes = []any{
	(*ReadStorageObjectsRequest)(nil),            // 0: ultimate.server.api.ReadStorageObjectsRequest
	(*StorageObject)(nil),                        // 1: ultimate.server.api.StorageObject
	(*StorageObjects)(nil),                       // 2: ultimate.server.api.StorageObjects
	(*WriteStorageObjectsRequest)(nil),           // 3: ultimate.server.api.WriteStorageObjectsRequest
	(*StorageObjectAck)(nil),                     // 4: ultimate.server.api.StorageObjectAck
	(*StorageObjectAcks)(nil),                    // 5: ultimate.server.api.StorageObjectAcks
	(*DeleteStorageObjectsRequest)(nil),          // 6: ultimate.server.api.DeleteStorageObjectsRequest
	(*ListStorageObjectsRequest)(nil),            // 7: ultimate.server.api.ListStorageObjectsRequest
	(*StorageObjectList)(nil),                    // 8: ultimate.server.api.StorageObjectList
	(*ReadStorageObjectsRequest_ReadOp)(nil),     // 9: ultimate.server.api.ReadStorageObjectsRequest.ReadOp
	(*WriteStorageObjectsRequest_WriteOp)(nil),   // 10: ultimate.server.api.WriteStorageObjectsRequest.WriteOp
	(*DeleteStorageObjectsRequest_DeleteOp)(nil), // 11: ultimate.server.api.DeleteStorageObjectsRequest.DeleteOp
	(*timestamppb.Timestamp)(nil),                // 12: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),                        // 13: google.protobuf.Empty
}
var file_api_storage_proto_depIdxs = []int32{
	9,  // 0: ultimate.server.api.ReadStorageObjectsRequest.object_ids:type_name -> ultimate.server.api.ReadStorageObjectsRequest.ReadOp
	12, // 1: ultimate.server.api.StorageObject.create_time:type_name -> google.protobuf.Timestamp
	12, // 2: ultimate.server.api.StorageObject.update_time:type_name -> google.protobuf.Timestamp
	1,  // 3: ultimate.server.api.StorageObjects.objects:type_name -> ultimate.server.api.StorageObject
	10, // 4: ultimate.server.api.WriteStorageObjectsRequest.objects:type_name -> ultimate.server.api.WriteStorageObjectsRequest.WriteOp
	12, // 5: ultimate.server.api.StorageObjectAck.create_time:type_name -> google.protobuf.Timestamp
	12, // 6: ultimate.server.api.StorageObjectAck.update_time:type_name -> google.protobuf.Timestamp
	4,  // 7: ultimate.server.api.StorageObjectAcks.acks:type_name -> ultimate.server.api.StorageObjectAck
	11, // 8: ultimate.server.api.DeleteStorageObjectsRequest.object_ids:type_name -> ultimate.server.api.DeleteStorageObjectsRequest.DeleteOp
	1,  // 9: ultimate.server.api.StorageObjectList.objects:type_name -> ultimate.server.api.StorageObject
	0,  // 10: ultimate.server.api.StorageService.ReadStorageObjects:input_type -> ultimate.server.api.ReadStorageObjectsRequest
	3,  // 11: ultimate.server.api.StorageService.WriteStorageObjects:input_type -> ultimate.server.api.WriteStorageObjectsRequest
	6,  // 12: ultimate.server.api.StorageService.DeleteStorageObjects:input_type -> ultimate.server.api.DeleteStorageObjectsRequest
	7,  // 13: ultimate.server.api.StorageService.ListStorageObjects:input_type -> ultimate.server.api.ListStorageObjectsRequest
	2,  // 14: ultimate.server.api.StorageService.ReadStorageObjects:output_type -> ultimate.server.api.StorageObjects
	5,  // 15: ultimate.server.api.StorageService.WriteStorageObjects:output_type -> ultimate.server.api.StorageObjectAcks
	13, // 16: ultimate.server.api.StorageService.DeleteStorageObjects:output_type -> google.protobuf.Empty
	8,  // 17: ultimate.server.api.StorageService.ListStorageObjects:output_type -> ultimate.server.api.StorageObjectList
	14, // [14:18] is the sub-list for method output_type
	10, // [10:14] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_api_storage_proto_init() }
func file_api_storage_proto_init() {
	if File_api_storage_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_storage_proto_rawDesc), len(file_api_storage_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_storage_proto_goTypes,
		DependencyIndexes: file_api_storage_proto_depIdxs,
		MessageInfos:      file_api_storage_proto_msgTypes,
	}.Build()
	File_api_storage_proto = out.File
	file_api_storage_proto_goTypes = nil
	file_api_storage_proto_depIdxs = nil
}
