// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: api/console/console.proto

package consolepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ATTENTION: Do not modify the order of this enum. Append only.
type AclResources int32

const (
	AclResources_ACCOUNT             AclResources = 0
	AclResources_ACCOUNT_WALLET      AclResources = 1
	AclResources_ACCOUNT_EXPORT      AclResources = 2
	AclResources_ACCOUNT_FRIENDS     AclResources = 3
	AclResources_ACCOUNT_GROUPS      AclResources = 4
	AclResources_ACCOUNT_NOTES       AclResources = 5
	AclResources_ACL_TEMPLATE        AclResources = 6
	AclResources_ALL_ACCOUNTS        AclResources = 7
	AclResources_ALL_DATA            AclResources = 8
	AclResources_ALL_STORAGE         AclResources = 9
	AclResources_API_EXPLORER        AclResources = 10
	AclResources_AUDIT_LOG           AclResources = 11
	AclResources_CONFIGURATION       AclResources = 12
	AclResources_CHANNEL_MESSAGE     AclResources = 13
	AclResources_USER                AclResources = 14
	AclResources_GROUP               AclResources = 15
	AclResources_IN_APP_PURCHASE     AclResources = 16
	AclResources_LEADERBOARD         AclResources = 17
	AclResources_LEADERBOARD_RECORD  AclResources = 18
	AclResources_MATCH               AclResources = 19
	AclResources_NOTIFICATION        AclResources = 20
	AclResources_SATORI_MESSAGE      AclResources = 21
	AclResources_SETTINGS            AclResources = 22
	AclResources_STORAGE_DATA        AclResources = 23
	AclResources_STORAGE_DATA_IMPORT AclResources = 24
	AclResources_HIRO_INVENTORY      AclResources = 25
	AclResources_HIRO_PROGRESSION    AclResources = 26
	AclResources_HIRO_ECONOMY        AclResources = 27
	AclResources_HIRO_STATS          AclResources = 28
	AclResources_HIRO_ENERGY         AclResources = 29
)

// Enum value maps for AclResources.
var (
	AclResources_name = map[int32]string{
		0:  "ACCOUNT",
		1:  "ACCOUNT_WALLET",
		2:  "ACCOUNT_EXPORT",
		3:  "ACCOUNT_FRIENDS",
		4:  "ACCOUNT_GROUPS",
		5:  "ACCOUNT_NOTES",
		6:  "ACL_TEMPLATE",
		7:  "ALL_ACCOUNTS",
		8:  "ALL_DATA",
		9:  "ALL_STORAGE",
		10: "API_EXPLORER",
		11: "AUDIT_LOG",
		12: "CONFIGURATION",
		13: "CHANNEL_MESSAGE",
		14: "USER",
		15: "GROUP",
		16: "IN_APP_PURCHASE",
		17: "LEADERBOARD",
		18: "LEADERBOARD_RECORD",
		19: "MATCH",
		20: "NOTIFICATION",
		21: "SATORI_MESSAGE",
		22: "SETTINGS",
		23: "STORAGE_DATA",
		24: "STORAGE_DATA_IMPORT",
		25: "HIRO_INVENTORY",
		26: "HIRO_PROGRESSION",
		27: "HIRO_ECONOMY",
		28: "HIRO_STATS",
		29: "HIRO_ENERGY",
	}
	AclResources_value = map[string]int32{
		"ACCOUNT":             0,
		"ACCOUNT_WALLET":      1,
		"ACCOUNT_EXPORT":      2,
		"ACCOUNT_FRIENDS":     3,
		"ACCOUNT_GROUPS":      4,
		"ACCOUNT_NOTES":       5,
		"ACL_TEMPLATE":        6,
		"ALL_ACCOUNTS":        7,
		"ALL_DATA":            8,
		"ALL_STORAGE":         9,
		"API_EXPLORER":        10,
		"AUDIT_LOG":           11,
		"CONFIGURATION":       12,
		"CHANNEL_MESSAGE":     13,
		"USER":                14,
		"GROUP":               15,
		"IN_APP_PURCHASE":     16,
		"LEADERBOARD":         17,
		"LEADERBOARD_RECORD":  18,
		"MATCH":               19,
		"NOTIFICATION":        20,
		"SATORI_MESSAGE":      21,
		"SETTINGS":            22,
		"STORAGE_DATA":        23,
		"STORAGE_DATA_IMPORT": 24,
		"HIRO_INVENTORY":      25,
		"HIRO_PROGRESSION":    26,
		"HIRO_ECONOMY":        27,
		"HIRO_STATS":          28,
		"HIRO_ENERGY":         29,
	}
)

func (x AclResources) Enum() *AclResources {
	p := new(AclResources)
	*p = x
	return p
}

func (x AclResources) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AclResources) Descriptor() protoreflect.EnumDescriptor {
	return file_api_console_console_proto_enumTypes[0].Descriptor()
}

func (AclResources) Type() protoreflect.EnumType {
	return &file_api_console_console_proto_enumTypes[0]
}

func (x AclResources) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AclResources.Descriptor instead.
func (AclResources) EnumDescriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{0}
}

type AuthenticateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password      string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Totp          string                 `protobuf:"bytes,3,opt,name=totp,proto3" json:"totp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateRequest) Reset() {
	*x = AuthenticateRequest{}
	mi := &file_api_console_console_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateRequest) ProtoMessage() {}

func (x *AuthenticateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{0}
}

func (x *AuthenticateRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *AuthenticateRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *AuthenticateRequest) GetTotp() string {
	if x != nil {
		return x.Totp
	}
	return ""
}

type ConsoleSession struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AclBitmap     string                 `protobuf:"bytes,2,opt,name=acl_bitmap,json=aclBitmap,proto3" json:"acl_bitmap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConsoleSession) Reset() {
	*x = ConsoleSession{}
	mi := &file_api_console_console_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConsoleSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConsoleSession) ProtoMessage() {}

func (x *ConsoleSession) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConsoleSession.ProtoReflect.Descriptor instead.
func (*ConsoleSession) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{1}
}

func (x *ConsoleSession) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *ConsoleSession) GetAclBitmap() string {
	if x != nil {
		return x.AclBitmap
	}
	return ""
}

type AuthenticateLogoutRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuthenticateLogoutRequest) Reset() {
	*x = AuthenticateLogoutRequest{}
	mi := &file_api_console_console_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthenticateLogoutRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthenticateLogoutRequest) ProtoMessage() {}

func (x *AuthenticateLogoutRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthenticateLogoutRequest.ProtoReflect.Descriptor instead.
func (*AuthenticateLogoutRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{2}
}

func (x *AuthenticateLogoutRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type AccountId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountId) Reset() {
	*x = AccountId{}
	mi := &file_api_console_console_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountId) ProtoMessage() {}

func (x *AccountId) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountId.ProtoReflect.Descriptor instead.
func (*AccountId) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{3}
}

func (x *AccountId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GroupId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupId) Reset() {
	*x = GroupId{}
	mi := &file_api_console_console_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupId) ProtoMessage() {}

func (x *GroupId) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupId.ProtoReflect.Descriptor instead.
func (*GroupId) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{4}
}

func (x *GroupId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GroupUserId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUserId) Reset() {
	*x = GroupUserId{}
	mi := &file_api_console_console_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUserId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUserId) ProtoMessage() {}

func (x *GroupUserId) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUserId.ProtoReflect.Descriptor instead.
func (*GroupUserId) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{5}
}

func (x *GroupUserId) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *GroupUserId) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type NotificationId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationId) Reset() {
	*x = NotificationId{}
	mi := &file_api_console_console_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationId) ProtoMessage() {}

func (x *NotificationId) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationId.ProtoReflect.Descriptor instead.
func (*NotificationId) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{6}
}

func (x *NotificationId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type AclTemplateId struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AclTemplateId) Reset() {
	*x = AclTemplateId{}
	mi := &file_api_console_console_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AclTemplateId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AclTemplateId) ProtoMessage() {}

func (x *AclTemplateId) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AclTemplateId.ProtoReflect.Descriptor instead.
func (*AclTemplateId) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{7}
}

func (x *AclTemplateId) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListGroupsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListGroupsRequest) Reset() {
	*x = ListGroupsRequest{}
	mi := &file_api_console_console_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListGroupsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListGroupsRequest) ProtoMessage() {}

func (x *ListGroupsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListGroupsRequest.ProtoReflect.Descriptor instead.
func (*ListGroupsRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{8}
}

func (x *ListGroupsRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ListGroupsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListGroupsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type Group struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	LangTag       string                 `protobuf:"bytes,4,opt,name=lang_tag,json=langTag,proto3" json:"lang_tag,omitempty"`
	Open          bool                   `protobuf:"varint,5,opt,name=open,proto3" json:"open,omitempty"`
	EdgeCount     int32                  `protobuf:"varint,6,opt,name=edge_count,json=edgeCount,proto3" json:"edge_count,omitempty"`
	MaxCount      int32                  `protobuf:"varint,7,opt,name=max_count,json=maxCount,proto3" json:"max_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_api_console_console_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{9}
}

func (x *Group) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Group) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Group) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Group) GetLangTag() string {
	if x != nil {
		return x.LangTag
	}
	return ""
}

func (x *Group) GetOpen() bool {
	if x != nil {
		return x.Open
	}
	return false
}

func (x *Group) GetEdgeCount() int32 {
	if x != nil {
		return x.EdgeCount
	}
	return 0
}

func (x *Group) GetMaxCount() int32 {
	if x != nil {
		return x.MaxCount
	}
	return 0
}

type GroupList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Groups        []*Group               `protobuf:"bytes,1,rep,name=groups,proto3" json:"groups,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupList) Reset() {
	*x = GroupList{}
	mi := &file_api_console_console_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupList) ProtoMessage() {}

func (x *GroupList) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupList.ProtoReflect.Descriptor instead.
func (*GroupList) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{10}
}

func (x *GroupList) GetGroups() []*Group {
	if x != nil {
		return x.Groups
	}
	return nil
}

func (x *GroupList) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type GroupUser struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	State         int32                  `protobuf:"varint,3,opt,name=state,proto3" json:"state,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUser) Reset() {
	*x = GroupUser{}
	mi := &file_api_console_console_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUser) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUser) ProtoMessage() {}

func (x *GroupUser) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUser.ProtoReflect.Descriptor instead.
func (*GroupUser) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{11}
}

func (x *GroupUser) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GroupUser) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GroupUser) GetState() int32 {
	if x != nil {
		return x.State
	}
	return 0
}

type GroupUserList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*GroupUser           `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupUserList) Reset() {
	*x = GroupUserList{}
	mi := &file_api_console_console_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupUserList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupUserList) ProtoMessage() {}

func (x *GroupUserList) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupUserList.ProtoReflect.Descriptor instead.
func (*GroupUserList) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{12}
}

func (x *GroupUserList) GetUsers() []*GroupUser {
	if x != nil {
		return x.Users
	}
	return nil
}

type AddGroupUsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserIds       []string               `protobuf:"bytes,2,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddGroupUsersRequest) Reset() {
	*x = AddGroupUsersRequest{}
	mi := &file_api_console_console_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddGroupUsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddGroupUsersRequest) ProtoMessage() {}

func (x *AddGroupUsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddGroupUsersRequest.ProtoReflect.Descriptor instead.
func (*AddGroupUsersRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{13}
}

func (x *AddGroupUsersRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *AddGroupUsersRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type DeleteGroupUserRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GroupId       string                 `protobuf:"bytes,1,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteGroupUserRequest) Reset() {
	*x = DeleteGroupUserRequest{}
	mi := &file_api_console_console_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteGroupUserRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteGroupUserRequest) ProtoMessage() {}

func (x *DeleteGroupUserRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteGroupUserRequest.ProtoReflect.Descriptor instead.
func (*DeleteGroupUserRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteGroupUserRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *DeleteGroupUserRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type ListChannelMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChannelId     string                 `protobuf:"bytes,1,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListChannelMessagesRequest) Reset() {
	*x = ListChannelMessagesRequest{}
	mi := &file_api_console_console_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListChannelMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListChannelMessagesRequest) ProtoMessage() {}

func (x *ListChannelMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListChannelMessagesRequest.ProtoReflect.Descriptor instead.
func (*ListChannelMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{15}
}

func (x *ListChannelMessagesRequest) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ListChannelMessagesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListChannelMessagesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type ChannelMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	ChannelId     string                 `protobuf:"bytes,2,opt,name=channel_id,json=channelId,proto3" json:"channel_id,omitempty"`
	SenderId      string                 `protobuf:"bytes,3,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	Username      string                 `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	Content       string                 `protobuf:"bytes,5,opt,name=content,proto3" json:"content,omitempty"`
	CreateTime    int64                  `protobuf:"varint,6,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMessage) Reset() {
	*x = ChannelMessage{}
	mi := &file_api_console_console_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessage) ProtoMessage() {}

func (x *ChannelMessage) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessage.ProtoReflect.Descriptor instead.
func (*ChannelMessage) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{16}
}

func (x *ChannelMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *ChannelMessage) GetChannelId() string {
	if x != nil {
		return x.ChannelId
	}
	return ""
}

func (x *ChannelMessage) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ChannelMessage) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *ChannelMessage) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *ChannelMessage) GetCreateTime() int64 {
	if x != nil {
		return x.CreateTime
	}
	return 0
}

type ChannelMessageList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*ChannelMessage      `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChannelMessageList) Reset() {
	*x = ChannelMessageList{}
	mi := &file_api_console_console_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChannelMessageList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChannelMessageList) ProtoMessage() {}

func (x *ChannelMessageList) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChannelMessageList.ProtoReflect.Descriptor instead.
func (*ChannelMessageList) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{17}
}

func (x *ChannelMessageList) GetMessages() []*ChannelMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

func (x *ChannelMessageList) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

type DeleteChannelMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	Before        int64                  `protobuf:"varint,2,opt,name=before,proto3" json:"before,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteChannelMessagesRequest) Reset() {
	*x = DeleteChannelMessagesRequest{}
	mi := &file_api_console_console_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteChannelMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteChannelMessagesRequest) ProtoMessage() {}

func (x *DeleteChannelMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteChannelMessagesRequest.ProtoReflect.Descriptor instead.
func (*DeleteChannelMessagesRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{18}
}

func (x *DeleteChannelMessagesRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

func (x *DeleteChannelMessagesRequest) GetBefore() int64 {
	if x != nil {
		return x.Before
	}
	return 0
}

type ListNotificationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListNotificationsRequest) Reset() {
	*x = ListNotificationsRequest{}
	mi := &file_api_console_console_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListNotificationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListNotificationsRequest) ProtoMessage() {}

func (x *ListNotificationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListNotificationsRequest.ProtoReflect.Descriptor instead.
func (*ListNotificationsRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{19}
}

func (x *ListNotificationsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ListNotificationsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListNotificationsRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Subject       string                 `protobuf:"bytes,3,opt,name=subject,proto3" json:"subject,omitempty"`
	Content       string                 `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Code          int32                  `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_api_console_console_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{20}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *Notification) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *Notification) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

type NotificationList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotificationList) Reset() {
	*x = NotificationList{}
	mi := &file_api_console_console_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationList) ProtoMessage() {}

func (x *NotificationList) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationList.ProtoReflect.Descriptor instead.
func (*NotificationList) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{21}
}

func (x *NotificationList) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *NotificationList) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type SendNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserIds       []string               `protobuf:"bytes,1,rep,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Code          int32                  `protobuf:"varint,4,opt,name=code,proto3" json:"code,omitempty"`
	Persistent    bool                   `protobuf:"varint,5,opt,name=persistent,proto3" json:"persistent,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendNotificationRequest) Reset() {
	*x = SendNotificationRequest{}
	mi := &file_api_console_console_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendNotificationRequest) ProtoMessage() {}

func (x *SendNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendNotificationRequest.ProtoReflect.Descriptor instead.
func (*SendNotificationRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{22}
}

func (x *SendNotificationRequest) GetUserIds() []string {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *SendNotificationRequest) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *SendNotificationRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *SendNotificationRequest) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *SendNotificationRequest) GetPersistent() bool {
	if x != nil {
		return x.Persistent
	}
	return false
}

type UnlinkAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Provider      string                 `protobuf:"bytes,2,opt,name=provider,proto3" json:"provider,omitempty"` // email|device|apple|google|facebook|steam|custom|gamecenter|facebookinstantgame
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnlinkAccountRequest) Reset() {
	*x = UnlinkAccountRequest{}
	mi := &file_api_console_console_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnlinkAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnlinkAccountRequest) ProtoMessage() {}

func (x *UnlinkAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnlinkAccountRequest.ProtoReflect.Descriptor instead.
func (*UnlinkAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{23}
}

func (x *UnlinkAccountRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *UnlinkAccountRequest) GetProvider() string {
	if x != nil {
		return x.Provider
	}
	return ""
}

type AccountExport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountExport) Reset() {
	*x = AccountExport{}
	mi := &file_api_console_console_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountExport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountExport) ProtoMessage() {}

func (x *AccountExport) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountExport.ProtoReflect.Descriptor instead.
func (*AccountExport) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{24}
}

func (x *AccountExport) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AccountExport) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type AccountImport struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PayloadJson   string                 `protobuf:"bytes,2,opt,name=payload_json,json=payloadJson,proto3" json:"payload_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountImport) Reset() {
	*x = AccountImport{}
	mi := &file_api_console_console_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountImport) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountImport) ProtoMessage() {}

func (x *AccountImport) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountImport.ProtoReflect.Descriptor instead.
func (*AccountImport) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{25}
}

func (x *AccountImport) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AccountImport) GetPayloadJson() string {
	if x != nil {
		return x.PayloadJson
	}
	return ""
}

type SatoriListTemplatesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatoriListTemplatesRequest) Reset() {
	*x = SatoriListTemplatesRequest{}
	mi := &file_api_console_console_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatoriListTemplatesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatoriListTemplatesRequest) ProtoMessage() {}

func (x *SatoriListTemplatesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatoriListTemplatesRequest.ProtoReflect.Descriptor instead.
func (*SatoriListTemplatesRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{26}
}

func (x *SatoriListTemplatesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *SatoriListTemplatesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type SatoriTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Title         string                 `protobuf:"bytes,3,opt,name=title,proto3" json:"title,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatoriTemplate) Reset() {
	*x = SatoriTemplate{}
	mi := &file_api_console_console_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatoriTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatoriTemplate) ProtoMessage() {}

func (x *SatoriTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatoriTemplate.ProtoReflect.Descriptor instead.
func (*SatoriTemplate) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{27}
}

func (x *SatoriTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SatoriTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SatoriTemplate) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SatoriTemplate) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type SatoriListTemplatesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*SatoriTemplate      `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	Cursor        string                 `protobuf:"bytes,2,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatoriListTemplatesResponse) Reset() {
	*x = SatoriListTemplatesResponse{}
	mi := &file_api_console_console_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatoriListTemplatesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatoriListTemplatesResponse) ProtoMessage() {}

func (x *SatoriListTemplatesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatoriListTemplatesResponse.ProtoReflect.Descriptor instead.
func (*SatoriListTemplatesResponse) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{28}
}

func (x *SatoriListTemplatesResponse) GetTemplates() []*SatoriTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

func (x *SatoriListTemplatesResponse) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type SatoriSendDirectMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IdentityId    string                 `protobuf:"bytes,1,opt,name=identity_id,json=identityId,proto3" json:"identity_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	TemplateId    string                 `protobuf:"bytes,4,opt,name=template_id,json=templateId,proto3" json:"template_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatoriSendDirectMessageRequest) Reset() {
	*x = SatoriSendDirectMessageRequest{}
	mi := &file_api_console_console_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatoriSendDirectMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatoriSendDirectMessageRequest) ProtoMessage() {}

func (x *SatoriSendDirectMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatoriSendDirectMessageRequest.ProtoReflect.Descriptor instead.
func (*SatoriSendDirectMessageRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{29}
}

func (x *SatoriSendDirectMessageRequest) GetIdentityId() string {
	if x != nil {
		return x.IdentityId
	}
	return ""
}

func (x *SatoriSendDirectMessageRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *SatoriSendDirectMessageRequest) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *SatoriSendDirectMessageRequest) GetTemplateId() string {
	if x != nil {
		return x.TemplateId
	}
	return ""
}

type SatoriSendDirectMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SatoriSendDirectMessageResponse) Reset() {
	*x = SatoriSendDirectMessageResponse{}
	mi := &file_api_console_console_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SatoriSendDirectMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SatoriSendDirectMessageResponse) ProtoMessage() {}

func (x *SatoriSendDirectMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SatoriSendDirectMessageResponse.ProtoReflect.Descriptor instead.
func (*SatoriSendDirectMessageResponse) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{30}
}

func (x *SatoriSendDirectMessageResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SatoriSendDirectMessageResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type Config struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Config) Reset() {
	*x = Config{}
	mi := &file_api_console_console_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Config) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Config) ProtoMessage() {}

func (x *Config) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Config.ProtoReflect.Descriptor instead.
func (*Config) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{31}
}

func (x *Config) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

type RuntimeInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RpcIds        []string               `protobuf:"bytes,1,rep,name=rpc_ids,json=rpcIds,proto3" json:"rpc_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RuntimeInfo) Reset() {
	*x = RuntimeInfo{}
	mi := &file_api_console_console_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RuntimeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RuntimeInfo) ProtoMessage() {}

func (x *RuntimeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RuntimeInfo.ProtoReflect.Descriptor instead.
func (*RuntimeInfo) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{32}
}

func (x *RuntimeInfo) GetRpcIds() []string {
	if x != nil {
		return x.RpcIds
	}
	return nil
}

type EndpointList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Methods       []string               `protobuf:"bytes,1,rep,name=methods,proto3" json:"methods,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointList) Reset() {
	*x = EndpointList{}
	mi := &file_api_console_console_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointList) ProtoMessage() {}

func (x *EndpointList) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointList.ProtoReflect.Descriptor instead.
func (*EndpointList) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{33}
}

func (x *EndpointList) GetMethods() []string {
	if x != nil {
		return x.Methods
	}
	return nil
}

type CallApiEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	BodyJson      string                 `protobuf:"bytes,3,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallApiEndpointRequest) Reset() {
	*x = CallApiEndpointRequest{}
	mi := &file_api_console_console_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallApiEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallApiEndpointRequest) ProtoMessage() {}

func (x *CallApiEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallApiEndpointRequest.ProtoReflect.Descriptor instead.
func (*CallApiEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{34}
}

func (x *CallApiEndpointRequest) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *CallApiEndpointRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CallApiEndpointRequest) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

type CallApiEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BodyJson      string                 `protobuf:"bytes,1,opt,name=body_json,json=bodyJson,proto3" json:"body_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallApiEndpointResponse) Reset() {
	*x = CallApiEndpointResponse{}
	mi := &file_api_console_console_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallApiEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallApiEndpointResponse) ProtoMessage() {}

func (x *CallApiEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallApiEndpointResponse.ProtoReflect.Descriptor instead.
func (*CallApiEndpointResponse) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{35}
}

func (x *CallApiEndpointResponse) GetBodyJson() string {
	if x != nil {
		return x.BodyJson
	}
	return ""
}

type CallRpcEndpointRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRpcEndpointRequest) Reset() {
	*x = CallRpcEndpointRequest{}
	mi := &file_api_console_console_proto_msgTypes[36]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRpcEndpointRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRpcEndpointRequest) ProtoMessage() {}

func (x *CallRpcEndpointRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[36]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRpcEndpointRequest.ProtoReflect.Descriptor instead.
func (*CallRpcEndpointRequest) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{36}
}

func (x *CallRpcEndpointRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CallRpcEndpointRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CallRpcEndpointRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type CallRpcEndpointResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Payload       string                 `protobuf:"bytes,1,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CallRpcEndpointResponse) Reset() {
	*x = CallRpcEndpointResponse{}
	mi := &file_api_console_console_proto_msgTypes[37]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CallRpcEndpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CallRpcEndpointResponse) ProtoMessage() {}

func (x *CallRpcEndpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[37]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CallRpcEndpointResponse.ProtoReflect.Descriptor instead.
func (*CallRpcEndpointResponse) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{37}
}

func (x *CallRpcEndpointResponse) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type AclTemplate struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	AclBitmap     string                 `protobuf:"bytes,3,opt,name=acl_bitmap,json=aclBitmap,proto3" json:"acl_bitmap,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AclTemplate) Reset() {
	*x = AclTemplate{}
	mi := &file_api_console_console_proto_msgTypes[38]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AclTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AclTemplate) ProtoMessage() {}

func (x *AclTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[38]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AclTemplate.ProtoReflect.Descriptor instead.
func (*AclTemplate) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{38}
}

func (x *AclTemplate) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AclTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AclTemplate) GetAclBitmap() string {
	if x != nil {
		return x.AclBitmap
	}
	return ""
}

type AclTemplateList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Templates     []*AclTemplate         `protobuf:"bytes,1,rep,name=templates,proto3" json:"templates,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AclTemplateList) Reset() {
	*x = AclTemplateList{}
	mi := &file_api_console_console_proto_msgTypes[39]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AclTemplateList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AclTemplateList) ProtoMessage() {}

func (x *AclTemplateList) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[39]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AclTemplateList.ProtoReflect.Descriptor instead.
func (*AclTemplateList) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{39}
}

func (x *AclTemplateList) GetTemplates() []*AclTemplate {
	if x != nil {
		return x.Templates
	}
	return nil
}

type Setting struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ValueJson     string                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Setting) Reset() {
	*x = Setting{}
	mi := &file_api_console_console_proto_msgTypes[40]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Setting) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Setting) ProtoMessage() {}

func (x *Setting) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[40]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Setting.ProtoReflect.Descriptor instead.
func (*Setting) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{40}
}

func (x *Setting) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Setting) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

type SettingList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Settings      []*Setting             `protobuf:"bytes,1,rep,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingList) Reset() {
	*x = SettingList{}
	mi := &file_api_console_console_proto_msgTypes[41]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingList) ProtoMessage() {}

func (x *SettingList) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[41]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingList.ProtoReflect.Descriptor instead.
func (*SettingList) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{41}
}

func (x *SettingList) GetSettings() []*Setting {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Status struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Json          string                 `protobuf:"bytes,1,opt,name=json,proto3" json:"json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Status) Reset() {
	*x = Status{}
	mi := &file_api_console_console_proto_msgTypes[42]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Status) ProtoMessage() {}

func (x *Status) ProtoReflect() protoreflect.Message {
	mi := &file_api_console_console_proto_msgTypes[42]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Status.ProtoReflect.Descriptor instead.
func (*Status) Descriptor() ([]byte, []int) {
	return file_api_console_console_proto_rawDescGZIP(), []int{42}
}

func (x *Status) GetJson() string {
	if x != nil {
		return x.Json
	}
	return ""
}

var File_api_console_console_proto protoreflect.FileDescriptor

const file_api_console_console_proto_rawDesc = "" +
	"\n" +
	"\x19api/console/console.proto\x12\x17ultimate.server.console\x1a\x1bgoogle/protobuf/empty.proto\"a\n" +
	"\x13AuthenticateRequest\x12\x1a\n" +
	"\busername\x18\x01 \x01(\tR\busername\x12\x1a\n" +
	"\bpassword\x18\x02 \x01(\tR\bpassword\x12\x12\n" +
	"\x04totp\x18\x03 \x01(\tR\x04totp\"E\n" +
	"\x0eConsoleSession\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\x12\x1d\n" +
	"\n" +
	"acl_bitmap\x18\x02 \x01(\tR\taclBitmap\"1\n" +
	"\x19AuthenticateLogoutRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"\x1b\n" +
	"\tAccountId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x19\n" +
	"\aGroupId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"A\n" +
	"\vGroupUserId\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\" \n" +
	"\x0eNotificationId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\x1f\n" +
	"\rAclTemplateId\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"U\n" +
	"\x11ListGroupsRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\xb8\x01\n" +
	"\x05Group\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x19\n" +
	"\blang_tag\x18\x04 \x01(\tR\alangTag\x12\x12\n" +
	"\x04open\x18\x05 \x01(\bR\x04open\x12\x1d\n" +
	"\n" +
	"edge_count\x18\x06 \x01(\x05R\tedgeCount\x12\x1b\n" +
	"\tmax_count\x18\a \x01(\x05R\bmaxCount\"[\n" +
	"\tGroupList\x126\n" +
	"\x06groups\x18\x01 \x03(\v2\x1e.ultimate.server.console.GroupR\x06groups\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"V\n" +
	"\tGroupUser\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\x12\x14\n" +
	"\x05state\x18\x03 \x01(\x05R\x05state\"I\n" +
	"\rGroupUserList\x128\n" +
	"\x05users\x18\x01 \x03(\v2\".ultimate.server.console.GroupUserR\x05users\"L\n" +
	"\x14AddGroupUsersRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\tR\auserIds\"L\n" +
	"\x16DeleteGroupUserRequest\x12\x19\n" +
	"\bgroup_id\x18\x01 \x01(\tR\agroupId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\"i\n" +
	"\x1aListChannelMessagesRequest\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x01 \x01(\tR\tchannelId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\xc2\x01\n" +
	"\x0eChannelMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x1d\n" +
	"\n" +
	"channel_id\x18\x02 \x01(\tR\tchannelId\x12\x1b\n" +
	"\tsender_id\x18\x03 \x01(\tR\bsenderId\x12\x1a\n" +
	"\busername\x18\x04 \x01(\tR\busername\x12\x18\n" +
	"\acontent\x18\x05 \x01(\tR\acontent\x12\x1f\n" +
	"\vcreate_time\x18\x06 \x01(\x03R\n" +
	"createTime\"z\n" +
	"\x12ChannelMessageList\x12C\n" +
	"\bmessages\x18\x01 \x03(\v2'.ultimate.server.console.ChannelMessageR\bmessages\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\"H\n" +
	"\x1cDeleteChannelMessagesRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\x12\x16\n" +
	"\x06before\x18\x02 \x01(\x03R\x06before\"a\n" +
	"\x18ListNotificationsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\"\x7f\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\asubject\x18\x03 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x04 \x01(\tR\acontent\x12\x12\n" +
	"\x04code\x18\x05 \x01(\x05R\x04code\"w\n" +
	"\x10NotificationList\x12K\n" +
	"\rnotifications\x18\x01 \x03(\v2%.ultimate.server.console.NotificationR\rnotifications\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"\x9c\x01\n" +
	"\x17SendNotificationRequest\x12\x19\n" +
	"\buser_ids\x18\x01 \x03(\tR\auserIds\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject\x12\x18\n" +
	"\acontent\x18\x03 \x01(\tR\acontent\x12\x12\n" +
	"\x04code\x18\x04 \x01(\x05R\x04code\x12\x1e\n" +
	"\n" +
	"persistent\x18\x05 \x01(\bR\n" +
	"persistent\"K\n" +
	"\x14UnlinkAccountRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1a\n" +
	"\bprovider\x18\x02 \x01(\tR\bprovider\"K\n" +
	"\rAccountExport\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"B\n" +
	"\rAccountImport\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12!\n" +
	"\fpayload_json\x18\x02 \x01(\tR\vpayloadJson\"J\n" +
	"\x1aSatoriListTemplatesRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"`\n" +
	"\x0eSatoriTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05title\x18\x03 \x01(\tR\x05title\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"|\n" +
	"\x1bSatoriListTemplatesResponse\x12E\n" +
	"\ttemplates\x18\x01 \x03(\v2'.ultimate.server.console.SatoriTemplateR\ttemplates\x12\x16\n" +
	"\x06cursor\x18\x02 \x01(\tR\x06cursor\"\x8c\x01\n" +
	"\x1eSatoriSendDirectMessageRequest\x12\x1f\n" +
	"\videntity_id\x18\x01 \x01(\tR\n" +
	"identityId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x12\x1f\n" +
	"\vtemplate_id\x18\x04 \x01(\tR\n" +
	"templateId\"G\n" +
	"\x1fSatoriSendDirectMessageResponse\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error\"\x1c\n" +
	"\x06Config\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json\"&\n" +
	"\vRuntimeInfo\x12\x17\n" +
	"\arpc_ids\x18\x01 \x03(\tR\x06rpcIds\"(\n" +
	"\fEndpointList\x12\x18\n" +
	"\amethods\x18\x01 \x03(\tR\amethods\"f\n" +
	"\x16CallApiEndpointRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1b\n" +
	"\tbody_json\x18\x03 \x01(\tR\bbodyJson\"6\n" +
	"\x17CallApiEndpointResponse\x12\x1b\n" +
	"\tbody_json\x18\x01 \x01(\tR\bbodyJson\"[\n" +
	"\x16CallRpcEndpointRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"3\n" +
	"\x17CallRpcEndpointResponse\x12\x18\n" +
	"\apayload\x18\x01 \x01(\tR\apayload\"P\n" +
	"\vAclTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"acl_bitmap\x18\x03 \x01(\tR\taclBitmap\"U\n" +
	"\x0fAclTemplateList\x12B\n" +
	"\ttemplates\x18\x01 \x03(\v2$.ultimate.server.console.AclTemplateR\ttemplates\"<\n" +
	"\aSetting\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\"K\n" +
	"\vSettingList\x12<\n" +
	"\bsettings\x18\x01 \x03(\v2 .ultimate.server.console.SettingR\bsettings\"\x1c\n" +
	"\x06Status\x12\x12\n" +
	"\x04json\x18\x01 \x01(\tR\x04json*\xa5\x04\n" +
	"\fAclResources\x12\v\n" +
	"\aACCOUNT\x10\x00\x12\x12\n" +
	"\x0eACCOUNT_WALLET\x10\x01\x12\x12\n" +
	"\x0eACCOUNT_EXPORT\x10\x02\x12\x13\n" +
	"\x0fACCOUNT_FRIENDS\x10\x03\x12\x12\n" +
	"\x0eACCOUNT_GROUPS\x10\x04\x12\x11\n" +
	"\rACCOUNT_NOTES\x10\x05\x12\x10\n" +
	"\fACL_TEMPLATE\x10\x06\x12\x10\n" +
	"\fALL_ACCOUNTS\x10\a\x12\f\n" +
	"\bALL_DATA\x10\b\x12\x0f\n" +
	"\vALL_STORAGE\x10\t\x12\x10\n" +
	"\fAPI_EXPLORER\x10\n" +
	"\x12\r\n" +
	"\tAUDIT_LOG\x10\v\x12\x11\n" +
	"\rCONFIGURATION\x10\f\x12\x13\n" +
	"\x0fCHANNEL_MESSAGE\x10\r\x12\b\n" +
	"\x04USER\x10\x0e\x12\t\n" +
	"\x05GROUP\x10\x0f\x12\x13\n" +
	"\x0fIN_APP_PURCHASE\x10\x10\x12\x0f\n" +
	"\vLEADERBOARD\x10\x11\x12\x16\n" +
	"\x12LEADERBOARD_RECORD\x10\x12\x12\t\n" +
	"\x05MATCH\x10\x13\x12\x10\n" +
	"\fNOTIFICATION\x10\x14\x12\x12\n" +
	"\x0eSATORI_MESSAGE\x10\x15\x12\f\n" +
	"\bSETTINGS\x10\x16\x12\x10\n" +
	"\fSTORAGE_DATA\x10\x17\x12\x17\n" +
	"\x13STORAGE_DATA_IMPORT\x10\x18\x12\x12\n" +
	"\x0eHIRO_INVENTORY\x10\x19\x12\x14\n" +
	"\x10HIRO_PROGRESSION\x10\x1a\x12\x10\n" +
	"\fHIRO_ECONOMY\x10\x1b\x12\x0e\n" +
	"\n" +
	"HIRO_STATS\x10\x1c\x12\x0f\n" +
	"\vHIRO_ENERGY\x10\x1d2\xa5\x17\n" +
	"\aConsole\x12e\n" +
	"\fAuthenticate\x12,.ultimate.server.console.AuthenticateRequest\x1a'.ultimate.server.console.ConsoleSession\x12`\n" +
	"\x12AuthenticateLogout\x122.ultimate.server.console.AuthenticateLogoutRequest\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\n" +
	"ListGroups\x12*.ultimate.server.console.ListGroupsRequest\x1a\".ultimate.server.console.GroupList\x12L\n" +
	"\bGetGroup\x12 .ultimate.server.console.GroupId\x1a\x1e.ultimate.server.console.Group\x12G\n" +
	"\vDeleteGroup\x12 .ultimate.server.console.GroupId\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x10ListGroupMembers\x12 .ultimate.server.console.GroupId\x1a&.ultimate.server.console.GroupUserList\x12V\n" +
	"\rAddGroupUsers\x12-.ultimate.server.console.AddGroupUsersRequest\x1a\x16.google.protobuf.Empty\x12Z\n" +
	"\x0fDeleteGroupUser\x12/.ultimate.server.console.DeleteGroupUserRequest\x1a\x16.google.protobuf.Empty\x12R\n" +
	"\x12PromoteGroupMember\x12$.ultimate.server.console.GroupUserId\x1a\x16.google.protobuf.Empty\x12Q\n" +
	"\x11DemoteGroupMember\x12$.ultimate.server.console.GroupUserId\x1a\x16.google.protobuf.Empty\x12w\n" +
	"\x13ListChannelMessages\x123.ultimate.server.console.ListChannelMessagesRequest\x1a+.ultimate.server.console.ChannelMessageList\x12f\n" +
	"\x15DeleteChannelMessages\x125.ultimate.server.console.DeleteChannelMessagesRequest\x1a\x16.google.protobuf.Empty\x12q\n" +
	"\x11ListNotifications\x121.ultimate.server.console.ListNotificationsRequest\x1a).ultimate.server.console.NotificationList\x12U\n" +
	"\x12DeleteNotification\x12'.ultimate.server.console.NotificationId\x1a\x16.google.protobuf.Empty\x12\\\n" +
	"\x10SendNotification\x120.ultimate.server.console.SendNotificationRequest\x1a\x16.google.protobuf.Empty\x12V\n" +
	"\rUnlinkAccount\x12-.ultimate.server.console.UnlinkAccountRequest\x1a\x16.google.protobuf.Empty\x12[\n" +
	"\rExportAccount\x12\".ultimate.server.console.AccountId\x1a&.ultimate.server.console.AccountExport\x12O\n" +
	"\rImportAccount\x12&.ultimate.server.console.AccountImport\x1a\x16.google.protobuf.Empty\x12?\n" +
	"\rDeleteAllData\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12\x80\x01\n" +
	"\x13SatoriListTemplates\x123.ultimate.server.console.SatoriListTemplatesRequest\x1a4.ultimate.server.console.SatoriListTemplatesResponse\x12\x8c\x01\n" +
	"\x17SatoriSendDirectMessage\x127.ultimate.server.console.SatoriSendDirectMessageRequest\x1a8.ultimate.server.console.SatoriSendDirectMessageResponse\x12D\n" +
	"\tGetConfig\x12\x16.google.protobuf.Empty\x1a\x1f.ultimate.server.console.Config\x12J\n" +
	"\n" +
	"GetRuntime\x12\x16.google.protobuf.Empty\x1a$.ultimate.server.console.RuntimeInfo\x12Q\n" +
	"\x10ListApiEndpoints\x12\x16.google.protobuf.Empty\x1a%.ultimate.server.console.EndpointList\x12t\n" +
	"\x0fCallApiEndpoint\x12/.ultimate.server.console.CallApiEndpointRequest\x1a0.ultimate.server.console.CallApiEndpointResponse\x12t\n" +
	"\x0fCallRpcEndpoint\x12/.ultimate.server.console.CallRpcEndpointRequest\x1a0.ultimate.server.console.CallRpcEndpointResponse\x12T\n" +
	"\x10ListAclTemplates\x12\x16.google.protobuf.Empty\x1a(.ultimate.server.console.AclTemplateList\x12\\\n" +
	"\x0eAddAclTemplate\x12$.ultimate.server.console.AclTemplate\x1a$.ultimate.server.console.AclTemplate\x12S\n" +
	"\x11DeleteAclTemplate\x12&.ultimate.server.console.AclTemplateId\x1a\x16.google.protobuf.Empty\x12L\n" +
	"\fListSettings\x12\x16.google.protobuf.Empty\x1a$.ultimate.server.console.SettingList\x12S\n" +
	"\rUpdateSetting\x12 .ultimate.server.console.Setting\x1a .ultimate.server.console.Setting\x12D\n" +
	"\tGetStatus\x12\x16.google.protobuf.Empty\x1a\x1f.ultimate.server.console.StatusB1Z/ultimate-game-server/internal/console/consolepbb\x06proto3"

var (
	file_api_console_console_proto_rawDescOnce sync.Once
	file_api_console_console_proto_rawDescData []byte
)

func file_api_console_console_proto_rawDescGZIP() []byte {
	file_api_console_console_proto_rawDescOnce.Do(func() {
		file_api_console_console_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_console_console_proto_rawDesc), len(file_api_console_console_proto_rawDesc)))
	})
	return file_api_console_console_proto_rawDescData
}

var file_api_console_console_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_api_console_console_proto_msgTypes = make([]protoimpl.MessageInfo, 43)
var file_api_console_console_proto_goTypes = []any{
	(AclResources)(0),                       // 0: ultimate.server.console.AclResources
	(*AuthenticateRequest)(nil),             // 1: ultimate.server.console.AuthenticateRequest
	(*ConsoleSession)(nil),                  // 2: ultimate.server.console.ConsoleSession
	(*AuthenticateLogoutRequest)(nil),       // 3: ultimate.server.console.AuthenticateLogoutRequest
	(*AccountId)(nil),                       // 4: ultimate.server.console.AccountId
	(*GroupId)(nil),                         // 5: ultimate.server.console.GroupId
	(*GroupUserId)(nil),                     // 6: ultimate.server.console.GroupUserId
	(*NotificationId)(nil),                  // 7: ultimate.server.console.NotificationId
	(*AclTemplateId)(nil),                   // 8: ultimate.server.console.AclTemplateId
	(*ListGroupsRequest)(nil),               // 9: ultimate.server.console.ListGroupsRequest
	(*Group)(nil),                           // 10: ultimate.server.console.Group
	(*GroupList)(nil),                       // 11: ultimate.server.console.GroupList
	(*GroupUser)(nil),                       // 12: ultimate.server.console.GroupUser
	(*GroupUserList)(nil),                   // 13: ultimate.server.console.GroupUserList
	(*AddGroupUsersRequest)(nil),            // 14: ultimate.server.console.AddGroupUsersRequest
	(*DeleteGroupUserRequest)(nil),          // 15: ultimate.server.console.DeleteGroupUserRequest
	(*ListChannelMessagesRequest)(nil),      // 16: ultimate.server.console.ListChannelMessagesRequest
	(*ChannelMessage)(nil),                  // 17: ultimate.server.console.ChannelMessage
	(*ChannelMessageList)(nil),              // 18: ultimate.server.console.ChannelMessageList
	(*DeleteChannelMessagesRequest)(nil),    // 19: ultimate.server.console.DeleteChannelMessagesRequest
	(*ListNotificationsRequest)(nil),        // 20: ultimate.server.console.ListNotificationsRequest
	(*Notification)(nil),                    // 21: ultimate.server.console.Notification
	(*NotificationList)(nil),                // 22: ultimate.server.console.NotificationList
	(*SendNotificationRequest)(nil),         // 23: ultimate.server.console.SendNotificationRequest
	(*UnlinkAccountRequest)(nil),            // 24: ultimate.server.console.UnlinkAccountRequest
	(*AccountExport)(nil),                   // 25: ultimate.server.console.AccountExport
	(*AccountImport)(nil),                   // 26: ultimate.server.console.AccountImport
	(*SatoriListTemplatesRequest)(nil),      // 27: ultimate.server.console.SatoriListTemplatesRequest
	(*SatoriTemplate)(nil),                  // 28: ultimate.server.console.SatoriTemplate
	(*SatoriListTemplatesResponse)(nil),     // 29: ultimate.server.console.SatoriListTemplatesResponse
	(*SatoriSendDirectMessageRequest)(nil),  // 30: ultimate.server.console.SatoriSendDirectMessageRequest
	(*SatoriSendDirectMessageResponse)(nil), // 31: ultimate.server.console.SatoriSendDirectMessageResponse
	(*Config)(nil),                          // 32: ultimate.server.console.Config
	(*RuntimeInfo)(nil),                     // 33: ultimate.server.console.RuntimeInfo
	(*EndpointList)(nil),                    // 34: ultimate.server.console.EndpointList
	(*CallApiEndpointRequest)(nil),          // 35: ultimate.server.console.CallApiEndpointRequest
	(*CallApiEndpointResponse)(nil),         // 36: ultimate.server.console.CallApiEndpointResponse
	(*CallRpcEndpointRequest)(nil),          // 37: ultimate.server.console.CallRpcEndpointRequest
	(*CallRpcEndpointResponse)(nil),         // 38: ultimate.server.console.CallRpcEndpointResponse
	(*AclTemplate)(nil),                     // 39: ultimate.server.console.AclTemplate
	(*AclTemplateList)(nil),                 // 40: ultimate.server.console.AclTemplateList
	(*Setting)(nil),                         // 41: ultimate.server.console.Setting
	(*SettingList)(nil),                     // 42: ultimate.server.console.SettingList
	(*Status)(nil),                          // 43: ultimate.server.console.Status
	(*emptypb.Empty)(nil),                   // 44: google.protobuf.Empty
}
var file_api_console_console_proto_depIdxs = []int32{
	10, // 0: ultimate.server.console.GroupList.groups:type_name -> ultimate.server.console.Group
	12, // 1: ultimate.server.console.GroupUserList.users:type_name -> ultimate.server.console.GroupUser
	17, // 2: ultimate.server.console.ChannelMessageList.messages:type_name -> ultimate.server.console.ChannelMessage
	21, // 3: ultimate.server.console.NotificationList.notifications:type_name -> ultimate.server.console.Notification
	28, // 4: ultimate.server.console.SatoriListTemplatesResponse.templates:type_name -> ultimate.server.console.SatoriTemplate
	39, // 5: ultimate.server.console.AclTemplateList.templates:type_name -> ultimate.server.console.AclTemplate
	41, // 6: ultimate.server.console.SettingList.settings:type_name -> ultimate.server.console.Setting
	1,  // 7: ultimate.server.console.Console.Authenticate:input_type -> ultimate.server.console.AuthenticateRequest
	3,  // 8: ultimate.server.console.Console.AuthenticateLogout:input_type -> ultimate.server.console.AuthenticateLogoutRequest
	9,  // 9: ultimate.server.console.Console.ListGroups:input_type -> ultimate.server.console.ListGroupsRequest
	5,  // 10: ultimate.server.console.Console.GetGroup:input_type -> ultimate.server.console.GroupId
	5,  // 11: ultimate.server.console.Console.DeleteGroup:input_type -> ultimate.server.console.GroupId
	5,  // 12: ultimate.server.console.Console.ListGroupMembers:input_type -> ultimate.server.console.GroupId
	14, // 13: ultimate.server.console.Console.AddGroupUsers:input_type -> ultimate.server.console.AddGroupUsersRequest
	15, // 14: ultimate.server.console.Console.DeleteGroupUser:input_type -> ultimate.server.console.DeleteGroupUserRequest
	6,  // 15: ultimate.server.console.Console.PromoteGroupMember:input_type -> ultimate.server.console.GroupUserId
	6,  // 16: ultimate.server.console.Console.DemoteGroupMember:input_type -> ultimate.server.console.GroupUserId
	16, // 17: ultimate.server.console.Console.ListChannelMessages:input_type -> ultimate.server.console.ListChannelMessagesRequest
	19, // 18: ultimate.server.console.Console.DeleteChannelMessages:input_type -> ultimate.server.console.DeleteChannelMessagesRequest
	20, // 19: ultimate.server.console.Console.ListNotifications:input_type -> ultimate.server.console.ListNotificationsRequest
	7,  // 20: ultimate.server.console.Console.DeleteNotification:input_type -> ultimate.server.console.NotificationId
	23, // 21: ultimate.server.console.Console.SendNotification:input_type -> ultimate.server.console.SendNotificationRequest
	24, // 22: ultimate.server.console.Console.UnlinkAccount:input_type -> ultimate.server.console.UnlinkAccountRequest
	4,  // 23: ultimate.server.console.Console.ExportAccount:input_type -> ultimate.server.console.AccountId
	26, // 24: ultimate.server.console.Console.ImportAccount:input_type -> ultimate.server.console.AccountImport
	44, // 25: ultimate.server.console.Console.DeleteAllData:input_type -> google.protobuf.Empty
	27, // 26: ultimate.server.console.Console.SatoriListTemplates:input_type -> ultimate.server.console.SatoriListTemplatesRequest
	30, // 27: ultimate.server.console.Console.SatoriSendDirectMessage:input_type -> ultimate.server.console.SatoriSendDirectMessageRequest
	44, // 28: ultimate.server.console.Console.GetConfig:input_type -> google.protobuf.Empty
	44, // 29: ultimate.server.console.Console.GetRuntime:input_type -> google.protobuf.Empty
	44, // 30: ultimate.server.console.Console.ListApiEndpoints:input_type -> google.protobuf.Empty
	35, // 31: ultimate.server.console.Console.CallApiEndpoint:input_type -> ultimate.server.console.CallApiEndpointRequest
	37, // 32: ultimate.server.console.Console.CallRpcEndpoint:input_type -> ultimate.server.console.CallRpcEndpointRequest
	44, // 33: ultimate.server.console.Console.ListAclTemplates:input_type -> google.protobuf.Empty
	39, // 34: ultimate.server.console.Console.AddAclTemplate:input_type -> ultimate.server.console.AclTemplate
	8,  // 35: ultimate.server.console.Console.DeleteAclTemplate:input_type -> ultimate.server.console.AclTemplateId
	44, // 36: ultimate.server.console.Console.ListSettings:input_type -> google.protobuf.Empty
	41, // 37: ultimate.server.console.Console.UpdateSetting:input_type -> ultimate.server.console.Setting
	44, // 38: ultimate.server.console.Console.GetStatus:input_type -> google.protobuf.Empty
	2,  // 39: ultimate.server.console.Console.Authenticate:output_type -> ultimate.server.console.ConsoleSession
	44, // 40: ultimate.server.console.Console.AuthenticateLogout:output_type -> google.protobuf.Empty
	11, // 41: ultimate.server.console.Console.ListGroups:output_type -> ultimate.server.console.GroupList
	10, // 42: ultimate.server.console.Console.GetGroup:output_type -> ultimate.server.console.Group
	44, // 43: ultimate.server.console.Console.DeleteGroup:output_type -> google.protobuf.Empty
	13, // 44: ultimate.server.console.Console.ListGroupMembers:output_type -> ultimate.server.console.GroupUserList
	44, // 45: ultimate.server.console.Console.AddGroupUsers:output_type -> google.protobuf.Empty
	44, // 46: ultimate.server.console.Console.DeleteGroupUser:output_type -> google.protobuf.Empty
	44, // 47: ultimate.server.console.Console.PromoteGroupMember:output_type -> google.protobuf.Empty
	44, // 48: ultimate.server.console.Console.DemoteGroupMember:output_type -> google.protobuf.Empty
	18, // 49: ultimate.server.console.Console.ListChannelMessages:output_type -> ultimate.server.console.ChannelMessageList
	44, // 50: ultimate.server.console.Console.DeleteChannelMessages:output_type -> google.protobuf.Empty
	22, // 51: ultimate.server.console.Console.ListNotifications:output_type -> ultimate.server.console.NotificationList
	44, // 52: ultimate.server.console.Console.DeleteNotification:output_type -> google.protobuf.Empty
	44, // 53: ultimate.server.console.Console.SendNotification:output_type -> google.protobuf.Empty
	44, // 54: ultimate.server.console.Console.UnlinkAccount:output_type -> google.protobuf.Empty
	25, // 55: ultimate.server.console.Console.ExportAccount:output_type -> ultimate.server.console.AccountExport
	44, // 56: ultimate.server.console.Console.ImportAccount:output_type -> google.protobuf.Empty
	44, // 57: ultimate.server.console.Console.DeleteAllData:output_type -> google.protobuf.Empty
	29, // 58: ultimate.server.console.Console.SatoriListTemplates:output_type -> ultimate.server.console.SatoriListTemplatesResponse
	31, // 59: ultimate.server.console.Console.SatoriSendDirectMessage:output_type -> ultimate.server.console.SatoriSendDirectMessageResponse
	32, // 60: ultimate.server.console.Console.GetConfig:output_type -> ultimate.server.console.Config
	33, // 61: ultimate.server.console.Console.GetRuntime:output_type -> ultimate.server.console.RuntimeInfo
	34, // 62: ultimate.server.console.Console.ListApiEndpoints:output_type -> ultimate.server.console.EndpointList
	36, // 63: ultimate.server.console.Console.CallApiEndpoint:output_type -> ultimate.server.console.CallApiEndpointResponse
	38, // 64: ultimate.server.console.Console.CallRpcEndpoint:output_type -> ultimate.server.console.CallRpcEndpointResponse
	40, // 65: ultimate.server.console.Console.ListAclTemplates:output_type -> ultimate.server.console.AclTemplateList
	39, // 66: ultimate.server.console.Console.AddAclTemplate:output_type -> ultimate.server.console.AclTemplate
	44, // 67: ultimate.server.console.Console.DeleteAclTemplate:output_type -> google.protobuf.Empty
	42, // 68: ultimate.server.console.Console.ListSettings:output_type -> ultimate.server.console.SettingList
	41, // 69: ultimate.server.console.Console.UpdateSetting:output_type -> ultimate.server.console.Setting
	43, // 70: ultimate.server.console.Console.GetStatus:output_type -> ultimate.server.console.Status
	39, // [39:71] is the sub-list for method output_type
	7,  // [7:39] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_console_console_proto_init() }
func file_api_console_console_proto_init() {
	if File_api_console_console_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_console_console_proto_rawDesc), len(file_api_console_console_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   43,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_console_console_proto_goTypes,
		DependencyIndexes: file_api_console_console_proto_depIdxs,
		EnumInfos:         file_api_console_console_proto_enumTypes,
		MessageInfos:      file_api_console_console_proto_msgTypes,
	}.Build()
	File_api_console_console_proto = out.File
	file_api_console_console_proto_goTypes = nil
	file_api_console_console_proto_depIdxs = nil
}
